spring:
  application:
    name: crm-dexter-backend
  datasource:
    url:    jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.wyzwxrewrcvqawcjwfrf
    password: crm_dexter200
    driver-class-name: org.postgresql.Driver


    hikari:
      pool-name: CrmDexterHikariPool
      maximum-pool-size: ${DB_MAX_POOL_SIZE:5}
      minimum-idle: ${DB_MIN_IDLE:1}
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    show-sql: ${SHOW_SQL:true}
    hibernate:
      # Las tablas ya fueron creadas con supabase_crm_dexter.sql.
      ddl-auto: validate
    
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

        
server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  jwt:
    secret: hWECRrGIJQckGPfyEqGxesnfYlEz71nw5Ci14VEqLGt
    expiration-ms: 86400000
  otp:
    expiration-seconds: ${OTP_EXPIRATION_SECONDS:300}
  emailjs:
    service-id: ${EMAILJS_SERVICE_ID:service_8uxwfjw}
    template-id: ${EMAILJS_TEMPLATE_ID:template_tvavw6v}
    public-key: ${EMAILJS_PUBLIC_KEY:3C-4-tQn2-lJzNuyt}
    private-key: ${EMAILJS_PRIVATE_KEY:DxHc9ijMxtRjfABi93QBR}
